language: python
sudo: false
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
install:
    - pip install -r test-requirements.txt
script:
    py.test --pep8 --flakes --cov=matchmock
after_success:
    coveralls
